import { BarChart3, BookOpenCheck, CheckCircle2, ChevronRight, CircleHelp, ClipboardCheck, ClipboardList, FileSpreadsheet, PackageCheck, RotateCcw, Settings2, ShieldCheck, UsersRound, Wrench } from "lucide-react";
import { useEffect, useState } from "react";

type GuideItem = {
  title: string;
  description: string;
  steps: string[];
  icon: typeof BookOpenCheck;
  tone: string;
};

const adminGuides: GuideItem[] = [
  { title: "Khởi tạo dữ liệu và phân quyền", description: "Thiết lập nền tảng trước khi vận hành: Phòng Ban, Bộ Phận, Phân loại, Hãng, Nhà cung cấp và tài khoản nhân sự.", steps: ["Tạo Phòng Ban và Bộ Phận trong mục Phòng Ban & Bộ Phận.", "Khai báo Phân loại kèm tiền tố mã tài sản để hệ thống tự sinh mã.", "Gán vai trò, Phòng Ban và Bộ Phận cho từng nhân sự trong Quản lý nhân viên."], icon: UsersRound, tone: "bg-[#EAF3FF] text-[#2666A8]" },
  { title: "Quản lý danh mục tài sản", description: "Tạo, chỉnh sửa, tìm kiếm, xuất Excel và theo dõi vòng đời từng tài sản thuộc công ty.", steps: ["Tạo mới từng tài sản hoặc dùng Nhập Excel khi cần thêm nhiều dòng.", "Giữ nguyên ngày mua sau khi tài sản đã được tạo để bảo toàn lịch sử.", "Dùng bộ lọc, danh sách đã lọc và lịch sử thay đổi để rà soát dữ liệu."], icon: ClipboardList, tone: "bg-[#E6F6F2] text-[#087A6A]" },
  { title: "Bàn giao và thu hồi", description: "Cấp phát tài sản đúng người nhận, theo dõi trạng thái ký xác nhận và lưu biên bản.", steps: ["Tạo phiếu từ tài sản Sẵn có, chọn người nhận và thời hạn hoàn trả nếu cần.", "Theo dõi phiếu Chờ ký, Đang cấp phát và Đã hoàn trả trong Bàn giao & Cấp phát.", "Xử lý yêu cầu hoàn trả của nhân viên, bổ sung quyết định hoặc ghi chú khi từ chối."], icon: PackageCheck, tone: "bg-[#ECF8F7] text-[#0F8C8C]" },
  { title: "Bảo trì, báo hỏng và trả NCC", description: "Ghi nhận sự cố, tạo phiếu xử lý và tách riêng các tài sản đã trả nhà cung cấp.", steps: ["Chuyển trạng thái Bảo trì và nhập rõ lý do cần xử lý.", "Tạo hoặc cập nhật phiếu bảo trì cho đến khi hoàn tất.", "Chỉ dùng Trả nhà cung cấp khi tài sản không còn thuộc công ty; tài sản này sẽ không xuất hiện trong Kiểm kê."], icon: Wrench, tone: "bg-[#FFF5DC] text-[#A86B00]" },
  { title: "Kiểm kê tài sản", description: "Lập đợt, chọn phạm vi, xuất danh sách thực địa, nhập kết quả và chốt biên bản.", steps: ["Chọn Phòng Ban hoặc Phân loại, sau đó thêm tài sản đủ điều kiện vào đợt.", "Xuất Danh sách kiểm kê, ghi trạng thái thực tế/kết quả rồi Nhập file đã kiểm kê.", "Rà soát preview, ghi chú chênh lệch, chốt biên bản khi mọi tài sản đã có kết quả."], icon: ClipboardCheck, tone: "bg-[#F0F5F8] text-[#527089]" },
  { title: "Báo cáo và kiểm soát vận hành", description: "Theo dõi giá trị, cơ cấu tài sản, lịch sử hoạt động và xuất báo cáo theo phạm vi đã lọc.", steps: ["Chọn phạm vi Phòng Ban/Bộ Phận trong Báo cáo trước khi xuất Excel.", "Dùng Nhật ký hoạt động để tra cứu thay đổi theo loại hoạt động hoặc người thực hiện.", "Rà soát báo cáo tài sản trả NCC riêng khi đánh giá tài sản không còn thuộc doanh nghiệp."], icon: BarChart3, tone: "bg-[#EEF4FF] text-[#3B73B9]" },
  { title: "Cài đặt và nhận diện hệ thống", description: "Cập nhật thông tin công ty, logo, favicon, hiệu ứng và tùy chọn thông báo.", steps: ["Cập nhật thông tin thương hiệu trước khi xuất biên bản hoặc báo cáo chính thức.", "Kiểm tra logo, mã số thuế, địa chỉ và liên hệ để các biểu mẫu đồng nhất.", "Thiết lập loại thông báo nhận để nhóm quản trị không bỏ sót yêu cầu quan trọng."], icon: Settings2, tone: "bg-[#F4EEFF] text-[#7652AD]" },
];

const userGuides: GuideItem[] = [
  { title: "Xem tài sản đang được cấp phát", description: "Cổng nhân viên hiển thị các thiết bị bạn đang giữ, ngày nhận, hạn dự kiến và trạng thái hoàn trả.", steps: ["Đăng nhập bằng tài khoản được quản trị viên cấp.", "Mở phần Tài sản bạn đang giữ để xem tên, mã tài sản và mã phiếu.", "Đối chiếu thiết bị thực tế với thông tin hiển thị trước khi gửi yêu cầu."], icon: PackageCheck, tone: "bg-[#E6F6F2] text-[#087A6A]" },
  { title: "Gửi yêu cầu hoàn trả", description: "Khi không còn nhu cầu sử dụng, gửi yêu cầu hoàn trả trực tiếp cho quản trị viên.", steps: ["Chọn Yêu cầu hoàn trả tại đúng tài sản đang giữ.", "Nhập ghi chú về thời điểm hoặc tình trạng bàn giao nếu cần.", "Theo dõi nhãn Đang chờ duyệt cho đến khi có quyết định."], icon: RotateCcw, tone: "bg-[#EAF3FF] text-[#2666A8]" },
  { title: "Theo dõi kết quả và phản hồi", description: "Kết quả duyệt/từ chối được hiển thị trên cổng nhân viên và trong lịch sử hoàn trả.", steps: ["Đọc thông báo kết quả và ghi chú từ quản trị viên.", "Nếu bị từ chối, dùng vùng giải trình để bổ sung thông tin cần thiết.", "Chọn Đã xem sau khi đã đọc kết quả để hoàn tất theo dõi."], icon: CheckCircle2, tone: "bg-[#FFF5DC] text-[#A86B00]" },
  { title: "Sử dụng thông tin đúng cách", description: "Thông tin tài sản và lịch sử bàn giao là dữ liệu nội bộ, chỉ dùng cho mục đích công việc.", steps: ["Không chia sẻ mã tài sản, thông tin thiết bị hoặc biên bản cho người không có quyền.", "Báo ngay cho quản trị viên khi thông tin hiển thị không khớp với thiết bị thực tế.", "Đăng xuất khi dùng máy tính công cộng hoặc thiết bị dùng chung."], icon: ShieldCheck, tone: "bg-[#F0F5F8] text-[#527089]" },
];

function GuideGrid({ guides }: { guides: GuideItem[] }) {
  return <div className="grid gap-4 lg:grid-cols-2">{guides.map((guide, index) => { const Icon = guide.icon; return <article key={guide.title} className="rounded-xl border border-[#DFE9F0] bg-white p-5 shadow-[0_8px_24px_rgba(16,42,67,.04)]"><div className="flex items-start gap-3"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${guide.tone}`}><Icon size={19} /></div><div className="min-w-0"><div className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[#8AA0B6]">Bước {String(index + 1).padStart(2, "0")}</div><h2 className="mt-1 text-sm font-extrabold text-[#193B57]">{guide.title}</h2><p className="mt-1.5 text-xs leading-5 text-[#71869A]">{guide.description}</p></div></div><ol className="mt-4 space-y-2.5 border-t border-[#EDF2F5] pt-4">{guide.steps.map((step, stepIndex) => <li key={step} className="flex gap-2.5 text-xs leading-5 text-[#60758A]"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#F0F5F8] text-[10px] font-extrabold text-[#527089]">{stepIndex + 1}</span><span>{step}</span></li>)}</ol></article>; })}</div>;
}

export function HelpCenter() {
  const [audience, setAudience] = useState<"admin" | "user">("admin");
  const showingAdmin = audience === "admin";
  const guides = showingAdmin ? adminGuides : userGuides;

  return <div className="min-h-screen bg-[#F4F7FB] px-4 py-7 sm:px-6 lg:px-9 lg:py-8"><div className="mx-auto max-w-[1500px]"><header className="mb-7 rounded-2xl bg-[#102A43] p-6 text-white shadow-[0_18px_42px_rgba(16,42,67,.16)] sm:p-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2 text-[11px] font-extrabold uppercase tracking-[.16em] text-[#5ED3C8]"><BookOpenCheck size={15} />Knowledge base</div><h1 className="mt-3 font-display text-3xl font-extrabold tracking-[-.05em] sm:text-4xl">Trợ giúp & Hướng dẫn</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#B5C8D5]">Hướng dẫn thao tác theo vai trò để sử dụng AssetMaster nhất quán, an toàn và đúng quy trình.</p></div><div className="rounded-xl border border-white/15 bg-white/10 p-3 text-xs text-[#DCEAF5]"><div className="font-extrabold text-white">Cần hỗ trợ nhanh?</div><p className="mt-1 leading-5">Bắt đầu từ nhóm hướng dẫn phù hợp với vai trò của bạn.</p></div></div></header><section className="rounded-xl border border-[#DFE9F0] bg-white p-3 shadow-[0_8px_24px_rgba(16,42,67,.04)]"><div className="grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => setAudience("admin")} className={`flex items-center gap-3 rounded-lg p-3 text-left transition ${showingAdmin ? "bg-[#EAF3FF] text-[#2666A8]" : "text-[#60758A] hover:bg-[#F7FAFC]"}`}><span className={`grid h-9 w-9 place-items-center rounded-lg ${showingAdmin ? "bg-white" : "bg-[#F0F5F8]"}`}><ShieldCheck size={18} /></span><span><span className="block text-xs font-extrabold">Hướng dẫn Quản trị viên</span><span className="mt-1 block text-[11px] text-[#71869A]">Thiết lập, quản lý và kiểm soát vận hành.</span></span><ChevronRight size={16} className="ml-auto" /></button><button type="button" onClick={() => setAudience("user")} className={`flex items-center gap-3 rounded-lg p-3 text-left transition ${!showingAdmin ? "bg-[#ECF8F7] text-[#087A6A]" : "text-[#60758A] hover:bg-[#F7FAFC]"}`}><span className={`grid h-9 w-9 place-items-center rounded-lg ${!showingAdmin ? "bg-white" : "bg-[#F0F5F8]"}`}><CircleHelp size={18} /></span><span><span className="block text-xs font-extrabold">Hướng dẫn Nhân viên</span><span className="mt-1 block text-[11px] text-[#71869A]">Theo dõi tài sản được cấp phát và hoàn trả.</span></span><ChevronRight size={16} className="ml-auto" /></button></div></section><section className="mt-5"><div className="mb-4 flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><div className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[#0F8C8C]">{showingAdmin ? "Admin playbook" : "Employee guide"}</div><h2 className="mt-1 font-display text-2xl font-extrabold text-[#102A43]">{showingAdmin ? "Quy trình dành cho Quản trị viên" : "Hướng dẫn dành cho Nhân viên"}</h2></div><div className="text-xs font-semibold text-[#71869A]">{guides.length} nhóm hướng dẫn</div></div><GuideGrid guides={guides} /></section></div></div>;
}

export function UserHelpDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; if (open) window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [open, onClose]);
  if (!open) return null;
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-[#102A43]/45 px-4 py-6 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="user-help-title" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="max-h-full w-full max-w-4xl overflow-hidden rounded-2xl border border-[#DFE9F0] bg-[#F4F7FB] shadow-2xl"><div className="flex items-start justify-between gap-4 border-b border-[#DFE9F0] bg-white px-5 py-4 sm:px-6"><div><div className="flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.14em] text-[#0F8C8C]"><CircleHelp size={14} />Cổng nhân viên</div><h2 id="user-help-title" className="mt-1 font-display text-xl font-extrabold text-[#102A43]">Hướng dẫn sử dụng</h2><p className="mt-1 text-xs text-[#71869A]">Các thao tác dành riêng cho tài khoản nhân viên.</p></div><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg text-lg font-bold text-[#71869A] transition hover:bg-[#F0F5F8] hover:text-[#193B57]" aria-label="Đóng hướng dẫn">×</button></div><div className="max-h-[min(70vh,720px)] overflow-y-auto p-5 sm:p-6"><GuideGrid guides={userGuides} /></div></div></div>;
}
