import { useState } from "react";
import { AlertTriangle, Building2, Factory, Pencil, Plus, Power, RefreshCw, Save, ShieldCheck, Truck, X } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

type VendorDraft = { name: string; contactName: string; phone: string; email: string };
type VendorEditor = ({ kind: "vendor" } & VendorDraft & { id: number }) | { kind: "brand"; id: number; name: string } | null;
const emptyVendor: VendorDraft = { name: "", contactName: "", phone: "", email: "" };

export function VendorBrandManagementPage() {
  const { user, loading } = useAuth();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const vendorsQuery = trpc.vendors.listAll.useQuery(undefined, { enabled: isAdmin });
  const brandsQuery = trpc.brands.listAll.useQuery(undefined, { enabled: isAdmin });
  const [vendorDraft, setVendorDraft] = useState<VendorDraft>(emptyVendor);
  const [brandName, setBrandName] = useState("");
  const [editor, setEditor] = useState<VendorEditor>(null);
  const vendors = vendorsQuery.data || [];
  const brands = brandsQuery.data || [];
  const refresh = () => { void utils.vendors.list.invalidate(); void utils.vendors.listAll.invalidate(); void utils.brands.list.invalidate(); void utils.brands.listAll.invalidate(); };
  const createVendor = trpc.vendors.create.useMutation({ onSuccess: () => { setVendorDraft(emptyVendor); refresh(); toast.success("Đã thêm Nhà cung cấp."); }, onError: (error) => toast.error(error.message || "Không thể thêm Nhà cung cấp.") });
  const createBrand = trpc.brands.create.useMutation({ onSuccess: () => { setBrandName(""); refresh(); toast.success("Đã thêm Hãng."); }, onError: (error) => toast.error(error.message || "Không thể thêm Hãng.") });
  const updateVendor = trpc.vendors.update.useMutation({ onSuccess: () => { setEditor(null); refresh(); toast.success("Đã cập nhật Nhà cung cấp."); }, onError: (error) => toast.error(error.message || "Không thể cập nhật Nhà cung cấp.") });
  const updateBrand = trpc.brands.update.useMutation({ onSuccess: () => { setEditor(null); refresh(); toast.success("Đã cập nhật Hãng."); }, onError: (error) => toast.error(error.message || "Không thể cập nhật Hãng.") });

  if (loading) return <PageState text="Đang kiểm tra quyền truy cập..." />;
  if (!isAdmin) return <PageState text="Chỉ quản trị viên mới được quản lý Nhà cung cấp và Hãng." forbidden />;
  if (vendorsQuery.isError || brandsQuery.isError) return <div className="min-h-screen bg-[#F4F7FB] px-4 py-7 sm:px-6 lg:px-9"><div className="mx-auto max-w-xl rounded-xl border border-[#F2D596] bg-[#FFF9EB] p-6"><div className="flex gap-3"><AlertTriangle className="mt-0.5 text-[#A86B00]" size={20} /><div><h1 className="font-display text-xl font-extrabold text-[#A86B00]">Không thể tải danh mục</h1><p className="mt-2 text-sm text-[#71869A]">{vendorsQuery.error?.message || brandsQuery.error?.message || "Vui lòng thử lại."}</p><button onClick={() => { void vendorsQuery.refetch(); void brandsQuery.refetch(); }} className="mt-4 inline-flex items-center gap-2 rounded-lg border border-[#F2D596] bg-white px-3 py-2 text-xs font-extrabold text-[#A86B00]"><RefreshCw size={14} />Thử lại</button></div></div></div></div>;

  const saveEditor = () => {
    if (!editor?.name.trim()) return toast.error("Vui lòng nhập tên.");
    if (editor.kind === "vendor") updateVendor.mutate({ id: editor.id, name: editor.name.trim(), contactName: editor.contactName.trim() || null, phone: editor.phone.trim() || null, email: editor.email.trim() || null });
    else updateBrand.mutate({ id: editor.id, name: editor.name.trim() });
  };

  return <div className="min-h-screen bg-[#F4F7FB] px-4 py-7 sm:px-6 lg:px-9 lg:py-8"><div className="mx-auto max-w-[1500px]">
    <header className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.16em] text-[#0F8C8C]"><span className="h-1.5 w-1.5 rounded-full bg-[#F0A516]" />Procurement directory</div><h1 className="font-display text-[28px] font-extrabold tracking-[-0.045em] text-[#102A43] sm:text-[34px]">Nhà cung cấp & Hãng</h1><p className="mt-1.5 max-w-2xl text-sm text-[#71869A]">Chuẩn hóa các đối tác mua sắm và hãng thiết bị để chọn nhanh trong hồ sơ tài sản.</p></div><div className="flex gap-3"><Stat label="Nhà cung cấp" value={vendors.filter((item) => item.isActive).length} /><Stat label="Hãng" value={brands.filter((item) => item.isActive).length} /></div></header>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-xl border border-[#DFE9F0] bg-white p-5 shadow-[0_8px_24px_rgba(16,42,67,0.045)] sm:p-6"><Heading icon={<Truck size={19} />} title="Thêm Nhà cung cấp" detail="Danh mục đối tác mua sắm; thông tin liên hệ là tùy chọn." /><form className="mt-5 grid gap-3 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); if (!vendorDraft.name.trim()) return toast.error("Vui lòng nhập tên Nhà cung cấp."); createVendor.mutate({ name: vendorDraft.name.trim(), contactName: vendorDraft.contactName.trim() || null, phone: vendorDraft.phone.trim() || null, email: vendorDraft.email.trim() || null }); }}><input className="field-input sm:col-span-2" placeholder="Tên Nhà cung cấp *" value={vendorDraft.name} onChange={(event) => setVendorDraft((current) => ({ ...current, name: event.target.value }))} /><input className="field-input" placeholder="Người liên hệ" value={vendorDraft.contactName} onChange={(event) => setVendorDraft((current) => ({ ...current, contactName: event.target.value }))} /><input className="field-input" placeholder="Số điện thoại" value={vendorDraft.phone} onChange={(event) => setVendorDraft((current) => ({ ...current, phone: event.target.value }))} /><input className="field-input sm:col-span-2" placeholder="Email liên hệ" value={vendorDraft.email} onChange={(event) => setVendorDraft((current) => ({ ...current, email: event.target.value }))} /><button disabled={createVendor.isPending} className="sm:col-span-2 flex h-10 items-center justify-center gap-2 rounded-lg bg-[#0F8C8C] px-4 text-xs font-extrabold text-white disabled:opacity-60"><Plus size={15} />{createVendor.isPending ? "Đang thêm..." : "Thêm Nhà cung cấp"}</button></form></section>
      <section className="rounded-xl border border-[#DFE9F0] bg-white p-5 shadow-[0_8px_24px_rgba(16,42,67,0.045)] sm:p-6"><Heading icon={<Factory size={19} />} title="Thêm Hãng" detail="Ví dụ: Dell, Apple, HP hoặc Cisco." /><form className="mt-5 flex flex-col gap-3 sm:flex-row" onSubmit={(event) => { event.preventDefault(); if (!brandName.trim()) return toast.error("Vui lòng nhập tên Hãng."); createBrand.mutate({ name: brandName.trim() }); }}><input className="field-input min-w-0 flex-1" placeholder="Tên Hãng *" value={brandName} onChange={(event) => setBrandName(event.target.value)} /><button disabled={createBrand.isPending} className="flex h-10 shrink-0 items-center justify-center gap-2 rounded-lg bg-[#2666A8] px-4 text-xs font-extrabold text-white disabled:opacity-60"><Plus size={15} />{createBrand.isPending ? "Đang thêm..." : "Thêm Hãng"}</button></form></section></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><Directory title="Danh sách Nhà cung cấp" empty="Chưa có Nhà cung cấp." items={vendors} icon={<Truck size={17} />} tone="teal" render={(item) => editor?.kind === "vendor" && editor.id === item.id ? <VendorEditor editor={editor} onChange={setEditor} onSave={saveEditor} onCancel={() => setEditor(null)} /> : <><div className="min-w-0"><div className="truncate font-bold text-[#193B57]">{item.name}</div><div className="mt-1 text-[11px] text-[#71869A]">{item.contactName || "Chưa có người liên hệ"}{item.phone ? ` · ${item.phone}` : ""}</div><div className="text-[11px] text-[#8AA0B6]">{item.email || "Chưa có email"}</div></div><Actions active={item.isActive} onEdit={() => setEditor({ kind: "vendor", id: item.id, name: item.name, contactName: item.contactName || "", phone: item.phone || "", email: item.email || "" })} onToggle={() => updateVendor.mutate({ id: item.id, isActive: !item.isActive })} /></>} />
        <Directory title="Danh sách Hãng" empty="Chưa có Hãng." items={brands} icon={<Factory size={17} />} tone="blue" render={(item) => editor?.kind === "brand" && editor.id === item.id ? <BrandEditor editor={editor} onChange={setEditor} onSave={saveEditor} onCancel={() => setEditor(null)} /> : <><div className="min-w-0"><div className="truncate font-bold text-[#193B57]">{item.name}</div><div className="mt-1 text-[11px] text-[#71869A]">Dùng để phân loại nguồn gốc thiết bị.</div></div><Actions active={item.isActive} onEdit={() => setEditor({ kind: "brand", id: item.id, name: item.name })} onToggle={() => updateBrand.mutate({ id: item.id, isActive: !item.isActive })} /></>} />
      </div>
  </div></div>;
}

function PageState({ text, forbidden }: { text: string; forbidden?: boolean }) { return <div className="min-h-screen bg-[#F4F7FB] px-4 py-7 sm:px-6 lg:px-9"><div className="mx-auto max-w-xl rounded-xl border border-[#DFE9F0] bg-white p-6"><div className="flex items-center gap-3 text-[#102A43]">{forbidden ? <ShieldCheck size={22} className="text-[#A86B00]" /> : <RefreshCw size={22} className="animate-spin text-[#0F8C8C]" />}<h1 className="font-display text-xl font-extrabold">{forbidden ? "Không có quyền truy cập" : text}</h1></div>{forbidden && <p className="mt-3 text-sm text-[#71869A]">{text}</p>}</div></div>; }
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-[#DDE7F0] bg-white px-4 py-3 text-center"><div className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#8AA0B6]">{label}</div><div className="mt-1 font-display text-xl font-extrabold text-[#102A43]">{value}</div></div>; }
function Heading({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="flex items-start gap-3 border-b border-[#E7EEF3] pb-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#ECF8F7] text-[#087A6A]">{icon}</div><div><h2 className="font-display text-lg font-extrabold text-[#102A43]">{title}</h2><p className="mt-1 text-xs leading-5 text-[#71869A]">{detail}</p></div></div>; }
function Actions({ active, onEdit, onToggle }: { active: boolean; onEdit: () => void; onToggle: () => void }) { return <div className="flex shrink-0 gap-1"><button onClick={onEdit} className="rounded-md p-2 text-[#60758A] hover:bg-[#EAF3FF] hover:text-[#2666A8]" aria-label="Chỉnh sửa"><Pencil size={14} /></button><button onClick={onToggle} className={`rounded-md p-2 ${active ? "text-[#A86B00] hover:bg-[#FFF9EB]" : "text-[#087A6A] hover:bg-[#ECF8F7]"}`} aria-label={active ? "Vô hiệu hóa" : "Kích hoạt"}><Power size={14} /></button></div>; }
function Directory<T extends { id: number; name: string; isActive: boolean }>({ title, empty, items, icon, tone, render }: { title: string; empty: string; items: T[]; icon: React.ReactNode; tone: "teal" | "blue"; render: (item: T) => React.ReactNode }) { return <section className="overflow-hidden rounded-xl border border-[#DFE9F0] bg-white shadow-[0_8px_24px_rgba(16,42,67,0.045)]"><div className="flex items-center gap-2 border-b border-[#E7EEF3] px-5 py-4"><span className={tone === "teal" ? "text-[#087A6A]" : "text-[#2666A8]"}>{icon}</span><h2 className="font-display text-lg font-extrabold text-[#102A43]">{title}</h2></div>{items.length ? <div className="divide-y divide-[#E7EEF3]">{items.map((item) => <article key={item.id} className={`flex items-start justify-between gap-3 px-5 py-4 ${item.isActive ? "" : "bg-[#FFF9FA]"}`}><div className="min-w-0 flex-1">{render(item)}</div></article>)}</div> : <p className="p-8 text-center text-sm text-[#8AA0B6]">{empty}</p>}</section>; }
function VendorEditor({ editor, onChange, onSave, onCancel }: { editor: Extract<VendorEditor, { kind: "vendor" }>; onChange: (value: VendorEditor) => void; onSave: () => void; onCancel: () => void }) { return <div className="grid gap-2"><input className="field-input h-8" value={editor.name} onChange={(event) => onChange({ ...editor, name: event.target.value })} /><div className="grid gap-2 sm:grid-cols-2"><input className="field-input h-8" placeholder="Người liên hệ" value={editor.contactName} onChange={(event) => onChange({ ...editor, contactName: event.target.value })} /><input className="field-input h-8" placeholder="Số điện thoại" value={editor.phone} onChange={(event) => onChange({ ...editor, phone: event.target.value })} /></div><input className="field-input h-8" placeholder="Email" value={editor.email} onChange={(event) => onChange({ ...editor, email: event.target.value })} /><div className="flex justify-end gap-2"><button onClick={onCancel} className="rounded-md border border-[#DDE7F0] px-3 py-1.5 text-xs font-bold text-[#60758A]"><X size={13} /></button><button onClick={onSave} className="rounded-md bg-[#0F8C8C] px-3 py-1.5 text-xs font-bold text-white"><Save size={13} /></button></div></div>; }
function BrandEditor({ editor, onChange, onSave, onCancel }: { editor: Extract<VendorEditor, { kind: "brand" }>; onChange: (value: VendorEditor) => void; onSave: () => void; onCancel: () => void }) { return <div className="flex gap-2"><input className="field-input h-8 min-w-0 flex-1" value={editor.name} onChange={(event) => onChange({ ...editor, name: event.target.value })} /><button onClick={onCancel} className="rounded-md border border-[#DDE7F0] px-3 text-[#60758A]"><X size={13} /></button><button onClick={onSave} className="rounded-md bg-[#0F8C8C] px-3 text-white"><Save size={13} /></button></div>; }
