import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const projectRoot = resolve(import.meta.dirname, "..");
const readProjectFile = (path: string) => readFileSync(resolve(projectRoot, path), "utf8");

describe("branch settings", () => {
  it("provides safe admin CRUD in System Settings without modifying the department hierarchy", () => {
    const schema = readProjectFile("drizzle/schema.ts");
    const database = readProjectFile("server/db.ts");
    const routers = readProjectFile("server/routers.ts");
    const settings = readProjectFile("client/src/components/BranchSettings.tsx");
    const home = readProjectFile("client/src/pages/Home.tsx");
    const employees = readProjectFile("client/src/pages/EmployeeManagementView.tsx");
    const supplyPreview = readProjectFile("client/src/components/SupplyIssueSlipManager.tsx");
    const supplyPdf = readProjectFile("client/src/lib/supplyIssueSlipPdf.ts");

    expect(schema).toContain('mysqlTable("branches"');
    expect(schema).toContain('branchId: int("branchId")');
    expect(database).toContain("getBranchUsageCounts");
    expect(database).toContain("deleteBranch");
    expect(database).toContain("const recipient = existing.recipientUserId");
    expect(database).toContain("branchId: recipient.branchId");
    expect(routers).toContain("branches: router");
    expect(routers).toContain("ensureInternalBranchEmail");
    expect(routers).toContain("Email Chi nhánh phải dùng tên miền nội bộ");
    expect(routers).toContain("confirmUsage");
    expect(routers).toContain("Mã Chi nhánh đã tồn tại");
    expect(settings).toContain("Quản lý Chi nhánh");
    expect(settings).toContain("branches.create");
    expect(settings).toContain("branches.update");
    expect(settings).toContain("branches.remove");
    expect(settings).toContain("Email Chi nhánh mới");
    expect(settings).toContain("Email liên hệ");
    expect(settings).toContain("internalEmailDomain");
    expect(settings).toContain("chưa thay đổi dữ liệu vận hành hiện hữu");
    expect(home).toContain("<BranchSettings />");
    expect(routers).toContain('getBranchByCode("HO-HEAD OFFICE")');
    expect(home).toContain("branchId: formData.branchId ?? null");
    expect(home).toContain("data-asset-branch");
    expect(home).toContain("AssetBranchSelector");
    expect(home).toContain("Tìm tên hoặc mã Chi nhánh");
    expect(home).not.toContain("data-asset-branch-anchor");
    expect(home).toContain('data-asset-branch className="min-w-0"');
    expect(home).toContain('<label className="field-label">Chi nhánh</label>');
    expect(home).not.toContain("Chi nhánh quản lý");
    expect(home).toContain("branchFilterCounts");
    expect(home).toContain("branchCounts={branchFilterCounts}");
    expect(home).toContain("branchLabel: asset.branchId ?");
    expect(home).toContain("data-asset-branch-badge");
    expect(home).toContain("data-asset-column-picker");
    expect(home).toContain("assetmaster-asset-catalog-visible-columns");
    expect(home).toContain("Khôi phục mặc định");
    expect(home).toContain('<th className="px-4 py-3.5">Chi nhánh</th>');
    expect(home).toContain("data-handover-reference");
    expect(home).toContain('w-[168px] px-3 py-3.5');
    expect(home).toContain('w-[144px] space-y-1');
    expect(home).toContain('overflow-hidden text-ellipsis whitespace-nowrap');
    expect(home).toContain('setRecoveryPdfRequest(String(item.recoveryCertificateNumber))');
    expect(home).not.toContain('`${item.referenceCode} · ${item.recoveryCertificateNumber}`');
    expect(home).toContain('min-w-[1000px]');
    expect(home).toContain("data-branch-asset-value-chart");
    expect(home).toContain("branchAssetValueSummary");
    expect(home).toContain('setBranchFilter(item.name); navigateTo("Danh mục tài sản")');
    expect(home).toContain('role="tooltip"');
    expect(home).toContain("Tỷ trọng: {percentage.toFixed(1)}%");
    expect(home.indexOf('key="asset-branch"')).toBeLessThan(home.indexOf('key="asset-status"'));
    expect(home).toContain("const inheritedEmployee = useMemo");
    expect(home).toContain("const inheritedEmployeeBranchId = inheritedEmployee?.branchId || null");
    expect(home).toContain("const assetEmployeesQuery = trpc.employees.list.useQuery()");
    expect(home).toContain("holderUserId: asset.holderUserId ?? null");
    expect(home).toContain("if (formData.holderUserId)");
    expect(home).toContain("item.id === formData.holderUserId");
    expect(home).toContain('normalize("NFC")');
    expect(home).toContain("setFormData((current) => ({ ...current, branchId: inheritedEmployeeBranchId }))");
    expect(home).toContain("isLocked={Boolean(inheritedEmployeeBranchId)}");
    expect(home).toContain("disabled={isLocked}");
    expect(home).toContain("Theo Nhân sự");
    expect(home).toContain("Chi nhánh được lấy từ hồ sơ Nhân sự đã chọn.");
    expect(home).toContain("const employeeBranchForAsset = useMemo");
    expect(home).toContain("trpc.employees.list.useQuery");
    expect(home).toContain('["Chi nhánh nhân sự", employeeBranchForAsset]');
    expect(home).toContain("const employeeDepartmentForAsset = useMemo");
    expect(home).toContain('["Phòng ban người giữ", employeeDepartmentForAsset]');
    expect(home).toContain("Không tìm thấy trong hồ sơ Nhân sự");
    expect(home).toContain("AssetAllocationHistory");
    expect(home).toContain("data-asset-allocation-history");
    expect(home).toContain('["holder", "branchId", "branch_id"]');
    expect(home).not.toContain("hideDepartmentsWithoutHandovers");
    expect(home).not.toContain('document.querySelector<HTMLElement>("[data-asset-modal]")');
    expect(employees).toContain("employees.updateBranch");
    expect(employees).toContain("data-employee-branch");
    expect(employees).toContain("EmployeeBranchAllocation");
    expect(employees).not.toContain("document.createElement");
    expect(employees).toContain('searchPlaceholder="Tìm tên hoặc mã Chi nhánh..."');
    expect(employees.indexOf('className="mt-4 rounded-xl border border-[#E7EEF3] p-4"><div className="flex items-center gap-2"><FolderTree')).toBeLessThan(employees.indexOf('data-employee-branch className="mt-4 rounded-xl border border-[#E7EEF3] p-4"'));
    expect(home).toContain("const [branchFilter, setBranchFilter]");
    expect(home).toContain("matchesBranch");
    expect(home).toContain("branchId: asset.branchId ?? null");
    expect(home).toContain("asset.branchId === selectedBranchId");
    expect(home).toContain("branchOptions");
    expect(home).toContain("onBranchChange");
    expect(home).toContain('"Chi nhánh": item.branch || "Chưa gán"');
    expect(supplyPreview).toContain("data-handover-recipient-branch");
    expect(supplyPreview).toContain("const recipientEmployee = handover");
    expect(supplyPreview).not.toContain("Chi nhánh tài sản:");
    expect(supplyPdf).toContain("const dividerY = Math.max(39, 25 + companyLines.length * 5 + 3)");
    expect(supplyPdf).toContain("const titleY = dividerY + 12");
    expect(home).toContain('<th className="px-4 py-3.5">Chi nhánh</th>');
    expect(home).toContain('["Chi nhánh", item.branch || "Chưa gán"]');
    const operations = readProjectFile("client/src/pages/OperationsModules.tsx");
    expect(operations).toContain("branchNameForAsset");
    expect(operations).toContain('"Chi nhánh": branchNameForAsset(asset)');
    expect(operations).toContain("Chi nhánh: ${row.branchName}");
    const handoverPdf = readProjectFile("client/src/lib/handoverAssetPdf.ts");
    const supplyIssues = readProjectFile("client/src/components/SupplyIssueSlipManager.tsx");
    expect(handoverPdf).toContain("branchName?: string | null");
    expect(handoverPdf).toContain('["Chi nhánh", input.branchName || "Chưa gán"]');
    expect(supplyIssues).toContain("const branch = recipientEmployee?.branchId");
    expect(supplyIssues).toContain("const branchEmail = branch?.email || undefined");
    expect(supplyIssues).toContain("email: branchEmail || company?.email");
    expect(supplyIssues).toContain("branchName, recipientName");
    expect(supplyIssues).not.toContain("Chi nhánh tài sản:");
    expect(home).toContain('get("handoverId")');
    expect(home).toContain("handoverBranchFilter");
    expect(home).toContain("HandoverBranchAutoField");
    expect(home).toContain('searchPlaceholder="Tìm tên Chi nhánh..."');
    expect(home).toContain("searchPlaceholder=\"Tìm tên Chi nhánh...\"");
    expect(home).toContain("Tự động lấy theo hồ sơ nhân sự.");
    expect(home).not.toContain("createRoot(host)");
    expect(operations).toContain('get("auditSession")');
    expect(operations).toContain("auditBranchFilter");
    expect(operations).toContain("setAuditBranchFilter");
    expect(operations).toContain("filteredAuditExportRows");
    expect(operations).toContain("exportFilteredAuditExcel");
    expect(operations).toContain("auditBranchOptions.find");
    expect(operations).toContain('<th className="px-4 py-3">Chi nhánh</th>');
    expect(operations).toContain('searchPlaceholder="Tìm tên hoặc mã Chi nhánh..."');
    expect(operations).not.toContain("createRoot(host)");
    const previewHost = readProjectFile("client/src/components/ExportPreviewHost.tsx");
    expect(previewHost).toContain("z-[1000]");
  });
});
