import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const projectRoot = resolve(import.meta.dirname, "..");
const readProjectFile = (path: string) => readFileSync(resolve(projectRoot, path), "utf8");

describe("branch settings", () => {
  it("provides safe admin CRUD in System Settings without modifying the department hierarchy", () => {
    const schema = readProjectFile("drizzle/schema.ts");
    const database = readProjectFile("server/db.ts");
    const routers = readProjectFile("server/routers.ts");
    const settings = readProjectFile("client/src/components/BranchSettings.tsx");
    const home = readProjectFile("client/src/pages/Home.tsx");
    const employees = readProjectFile("client/src/pages/EmployeeManagementView.tsx");

    expect(schema).toContain('mysqlTable("branches"');
    expect(schema).toContain('branchId: int("branchId")');
    expect(database).toContain("getBranchUsageCounts");
    expect(database).toContain("deleteBranch");
    expect(routers).toContain("branches: router");
    expect(routers).toContain("confirmUsage");
    expect(routers).toContain("Mã Chi nhánh đã tồn tại");
    expect(settings).toContain("Quản lý Chi nhánh");
    expect(settings).toContain("branches.create");
    expect(settings).toContain("branches.update");
    expect(settings).toContain("branches.remove");
    expect(settings).toContain("chưa thay đổi dữ liệu vận hành hiện hữu");
    expect(home).toContain("<BranchSettings />");
    expect(routers).toContain('getBranchByCode("HO-HEAD OFFICE")');
    expect(home).toContain("branchId: formData.branchId ?? null");
    expect(home).toContain("data-asset-branch");
    expect(home).toContain("AssetBranchSelector");
    expect(home).toContain("Tìm tên hoặc mã Chi nhánh");
    expect(home).not.toContain("data-asset-branch-anchor");
    expect(home).toContain('data-asset-branch className="min-w-0"');
    expect(home).toContain('<label className="field-label">Chi nhánh</label>');
    expect(home).not.toContain("Chi nhánh quản lý");
    expect(home).toContain("branchFilterCounts");
    expect(home).toContain("branchCounts={branchFilterCounts}");
    expect(home).toContain("data-branch-asset-value-chart");
    expect(home).toContain("branchAssetValueSummary");
    expect(home).toContain('setBranchFilter(item.name); navigateTo("Danh mục tài sản")');
    expect(home).toContain('role="tooltip"');
    expect(home).toContain("Tỷ trọng: {percentage.toFixed(1)}%");
    expect(home.indexOf('key="asset-branch"')).toBeLessThan(home.indexOf('key="asset-status"'));
    expect(home).toContain("const employeeBranchForAsset = useMemo");
    expect(home).toContain("trpc.employees.list.useQuery");
    expect(home).toContain('["Chi nhánh nhân sự", employeeBranchForAsset]');
    expect(home).toContain("Không tìm thấy trong hồ sơ Nhân sự");
    expect(home).not.toContain('document.querySelector<HTMLElement>("[data-asset-modal]")');
    expect(employees).toContain("employees.updateBranch");
    expect(employees).toContain("data-employee-branch");
    expect(employees).toContain("EmployeeBranchAllocation");
    expect(employees).not.toContain("document.createElement");
    expect(employees).toContain('searchPlaceholder="Tìm tên hoặc mã Chi nhánh..."');
    expect(employees.indexOf('className="mt-4 rounded-xl border border-[#E7EEF3] p-4"><div className="flex items-center gap-2"><FolderTree')).toBeLessThan(employees.indexOf('data-employee-branch className="mt-4 rounded-xl border border-[#E7EEF3] p-4"'));
    expect(home).toContain("const [branchFilter, setBranchFilter]");
    expect(home).toContain("matchesBranch");
    expect(home).toContain("branchId: asset.branchId ?? null");
    expect(home).toContain("asset.branchId === selectedBranchId");
    expect(home).toContain("branchOptions");
    expect(home).toContain("onBranchChange");
    expect(home).toContain('"Chi nhánh": item.branch || "Chưa gán"');
    expect(home).toContain('<th className="px-4 py-3.5">Chi nhánh</th>');
    expect(home).toContain('["Chi nhánh", item.branch || "Chưa gán"]');
    const operations = readProjectFile("client/src/pages/OperationsModules.tsx");
    expect(operations).toContain("branchNameForAsset");
    expect(operations).toContain('"Chi nhánh": branchNameForAsset(asset)');
    expect(operations).toContain("Chi nhánh: ${row.branchName}");
    const handoverPdf = readProjectFile("client/src/lib/handoverAssetPdf.ts");
    const supplyIssues = readProjectFile("client/src/components/SupplyIssueSlipManager.tsx");
    expect(handoverPdf).toContain("branchName?: string | null");
    expect(handoverPdf).toContain('["Chi nhánh", input.branchName || "Chưa gán"]');
    expect(supplyIssues).toContain("const branchName = handoverAsset?.branchId");
    expect(supplyIssues).toContain("branchName, recipientName");
    expect(supplyIssues).toContain("Chi nhánh tài sản:");
    expect(home).toContain('get("handoverId")');
    expect(home).toContain("handoverBranchFilter");
    expect(home).toContain("HandoverBranchAutoField");
    expect(home).toContain('searchPlaceholder="Tìm tên Chi nhánh..."');
    expect(home).toContain("searchPlaceholder=\"Tìm tên Chi nhánh...\"");
    expect(home).toContain("Tự động lấy theo hồ sơ nhân sự.");
    expect(home).not.toContain("createRoot(host)");
    expect(operations).toContain('get("auditSession")');
    expect(operations).toContain("auditBranchFilter");
    expect(operations).toContain("setAuditBranchFilter");
    expect(operations).toContain("filteredAuditExportRows");
    expect(operations).toContain("exportFilteredAuditExcel");
    expect(operations).toContain("auditBranchOptions.find");
    expect(operations).toContain('<th className="px-4 py-3">Chi nhánh</th>');
    expect(operations).toContain('searchPlaceholder="Tìm tên hoặc mã Chi nhánh..."');
    expect(operations).not.toContain("createRoot(host)");
    const previewHost = readProjectFile("client/src/components/ExportPreviewHost.tsx");
    expect(previewHost).toContain("z-[1000]");
  });
});
