import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

describe("Bản quyền & Dịch vụ", () => {
  it("registers the sidebar entry, deep link and management screen", () => {
    const home = readFileSync(resolve(process.cwd(), "client/src/pages/Home.tsx"), "utf8");

    expect(home).toContain('label: "Bản quyền & Dịch vụ"');
    expect(home).toContain('licenses: "Bản quyền & Dịch vụ"');
    expect(home).toContain('<LicensesServicesManagementView />');
  });

  it("provides licensing, assignment and service-expiry management flows", () => {
    const view = readFileSync(resolve(process.cwd(), "client/src/pages/LicensesServicesManagementView.tsx"), "utf8");
    const styles = readFileSync(resolve(process.cwd(), "client/src/index.css"), "utf8");

    expect(view).toContain("trpc.softwareLicenses.list.useQuery");
    expect(view).toContain("trpc.softwareLicenses.assign.useMutation");
    expect(view).toContain("trpc.softwareLicenses.create.useMutation");
    expect(view).toContain("trpc.softwareLicenses.documents.useQuery");
    expect(view).toContain("trpc.softwareLicenses.uploadDocument.useMutation");
    expect(view).toContain("trpc.softwareLicenses.removeDocument.useMutation");
    expect(view).toContain("LicenseDocumentControls");
    expect(view).toContain("Tệp đính kèm");
    expect(view).toContain("Tài liệu gia hạn");
    expect(view).toContain("Nhân bản Bản quyền");
    expect(view).toContain("licenseCode: \"\"");
    expect(view).toContain("khóa mới");
    expect(view).toContain("trpc.technologyServices.list.useQuery");
    expect(view).toContain("trpc.technologyVendors.list.useQuery");
    expect(view).toContain("trpc.technologyVendorContracts.list.useQuery");
    expect(view).toContain("TechnologyVendorDirectoryPanel");
    expect(view).toContain("Nhà cung cấp & Hợp đồng Công nghệ");
    expect(view).toContain("technologyVendorId");
    expect(view).toContain("technologyVendorContractId");
    const technologyDirectory = readFileSync(resolve(process.cwd(), "client/src/components/TechnologyVendorDirectoryPanel.tsx"), "utf8");
    expect(technologyDirectory).toContain("technologyVendors.usageStats.useQuery");
    expect(technologyDirectory).toContain("technologyVendorContracts.expiringAlerts.useQuery({ daysAhead: 30 })");
    expect(technologyDirectory).toContain("Bản quyền đang sử dụng");
    expect(technologyDirectory).toContain("Dịch vụ đang sử dụng");
    expect(technologyDirectory).toContain("Hợp đồng Công nghệ cần theo dõi");
    expect(technologyDirectory).toContain("technologyVendorContracts.documents.useQuery");
    expect(technologyDirectory).toContain("technologyVendorContracts.uploadDocument.useMutation");
    expect(technologyDirectory).toContain("technologyVendorContracts.removeDocument.useMutation");
    expect(technologyDirectory).toContain('accept="application/pdf,image/png,image/jpeg"');
    expect(technologyDirectory).toContain('type="file" multiple');
    expect(technologyDirectory).toContain("selectFiles(event.target.files || [])");
    expect(technologyDirectory).toContain("upload.mutateAsync");
    expect(technologyDirectory).toContain("Tải nhiều tệp");
    expect(technologyDirectory).toContain("tối đa 5 MB mỗi tệp");
    expect(technologyDirectory).toContain('aria-live="polite"');
    expect(technologyDirectory).toContain("Đã tải ${uploadedCount} tài liệu Hợp đồng.");
    expect(technologyDirectory).toContain("expiryFilter");
    expect(technologyDirectory).toContain("Sắp hết hạn");
    expect(technologyDirectory).toContain("Đã quá hạn");
    expect(technologyDirectory).toContain('onOpenChange={(open) => !open && setContractModal(null)}');
    expect(readFileSync(resolve(process.cwd(), "server/db.ts"), "utf8")).toContain("('active', 'expiring', 'expired')");
    expect(technologyDirectory).toContain('data-licenses-services-dialog="technology"');
    expect(technologyDirectory).toContain("data-technology-vendor-usage");
    expect(technologyDirectory).toContain('grid gap-3 sm:grid-cols-3');
    expect(technologyDirectory).toContain("data-technology-contract-alerts");
    expect(technologyDirectory).toContain("Quá hạn ${Math.abs(days)} ngày");
    expect(technologyDirectory).toContain("Còn ${days ?? 0} ngày");
    expect(view).toContain("Bản quyền sắp hết hạn");
    expect(view).toContain("Dịch vụ sắp hết hạn");
    expect(view).toContain("Đường truyền Internet");
    expect(view).toContain("Tên miền");
    expect(view).toContain("SSL");
    expect(view).toContain("data-license-services-filter-controls");
    expect(view).toContain('onClick={resetFilters} className="inline-flex h-9 shrink-0 items-center justify-center gap-2 whitespace-nowrap rounded-lg border border-[#DDE7F0] bg-white px-3 text-xs font-bold text-[#60758A] transition hover:bg-[#F7FAFC] active:scale-[.97]"');
    expect(view).toContain('<X size={14} />Xóa bộ lọc');
    expect(view).toContain('from "@/components/SearchableSelect"');
    expect(view).toContain("function StandardDropdown");
    expect(view).toContain("<StandardDropdown");
    expect((view.match(/<StandardDropdown/g) || []).length).toBe(18);
    expect(view).toContain("Tìm nhà cung cấp...");
    expect(view).toContain("Tìm chi nhánh...");
    expect(view).toContain("Tìm mã hoặc tên Tài sản...");
    expect(view).toContain("Tìm Nhân sự...");
    expect(view).toContain("Tìm loại tài liệu...");
    expect(view).toContain("TechnologyContractPortal");
    expect(view).toContain("Hợp đồng Công nghệ");
    expect(view).toContain("Tìm mã hoặc tên hợp đồng...");
    expect(view).toContain("value={assignmentForm.assetId}");
    expect(view).toContain("value={assignmentForm.userId}");
    expect(view).toContain("value={documentType}");
    expect(view).not.toContain("<select");
    expect(view).toContain("Tìm trạng thái...");
    expect(view).toContain("Tìm thời hạn...");
    expect(view).toContain("Tìm cách sắp xếp...");
    expect(view).toContain("Hết hạn trong 7 ngày");
    expect(view).toContain("Hạn gần nhất trước");
    expect(view).toContain("Mọi nhà cung cấp");
    expect(view).toContain("Mọi loại dịch vụ");
    expect(view).toContain("Mọi chi nhánh");
    expect(view).toContain("data-license-services-loading");
    expect(view).toContain("data-license-services-error");
    expect(view).toContain("data-license-services-directory-state");
    expect(view).toContain("Đang tải {label}");
    expect(view).toContain("Không thể tải {label}");
    expect(view).toContain("vendorUnavailable");
    expect(view).toContain("assignmentDirectoryUnavailable");
    expect(view).toContain("Không thể tải dữ liệu quản lý");
    expect(view).toContain("CenteredServiceDialogContent");
    expect(view).toContain('get("createLicense") === "1"');
    expect(view).toContain('data-licenses-services-dialog="service"');
    expect(view).toContain('<DialogContent data-licenses-services-dialog="service">');
    expect(view).toContain('<DialogContent data-licenses-services-dialog="license"');
    expect(view).toContain('className="field-label"');
    expect(view).toContain("data-expiry-overdue");
    expect(view).toContain("Quá hạn ${Math.abs(days)} ngày");
    expect(styles).toContain(".service-dialog-panel");
    expect(styles).toContain('[data-licenses-services-dialog="license"]');
    expect(styles).toContain('[data-licenses-services-dialog="service"]');
    expect(styles).toContain('[data-licenses-services-dialog="technology"]');
    expect(styles).toContain('[data-licenses-services-dialog="technology"] input[type="date"]');
    expect(view).toContain('import { DatePickerField } from "@/components/DatePickerField"');
    expect(view).toContain('import { CurrencyInput } from "@/components/CurrencyInput"');
    expect(view).toContain('<DatePickerField value={String(value ?? "")}');
    expect(view).toContain('<CurrencyInput {...inputProps} value={String(value ?? "")}');
    expect(view).toContain("showWords aria-label=\"Chi phí\"");
    expect(view).not.toContain("service-currency-input");
    expect(styles).toContain("place-items: center !important");
    expect(styles).toContain('[data-licenses-services-dialog="license"] .form-input');
    expect(styles).toContain("overflow-x: hidden !important");
    expect(styles).toContain("position: static");
    expect(styles).toContain("overflow: hidden !important");
    expect(styles).toContain("min-height: auto");
    expect(styles).toContain("margin: 1rem 0 0 !important");
    expect(styles).toContain(".form-button-primary");
    expect(styles).toContain(".form-button-secondary");
    expect(styles).toContain("License modal: fixed panel shell");
    expect(styles).toContain("height: min(48rem, calc(100dvh - 2rem)) !important");
    expect(styles).toContain("overflow-y: auto !important");
    expect(styles).toContain("height: 0;");
    expect(styles).toContain("min-height: 2.45rem");
    expect(styles).toContain("color: #A8B8C5");
    expect(readFileSync(resolve(process.cwd(), "client/src/components/ui/dialog.tsx"), "utf8")).toContain("license-service-dialog-panel relative flex");
    expect(styles).toContain('content: "BẢN QUYỀN & DỊCH VỤ"');
    expect(styles).toContain("license-service-dialog-close");
    const dialog = readFileSync(resolve(process.cwd(), "client/src/components/ui/dialog.tsx"), "utf8");
    expect(dialog).toContain('licenseServiceDialog === "license" || licenseServiceDialog === "service" || licenseServiceDialog === "technology"');
    expect(dialog).toContain("license-service-dialog-panel relative flex");
  });
});
