// @ts-nocheck
import { FileBarChart, PieChart as PieChartIcon } from "lucide-react";
import { formatCompactVnd, type CurrencyDisplayMode } from "@/lib/formatters";

const card = "rounded-xl border border-[#DFE9F0] bg-white shadow-[0_8px_24px_rgba(16,42,67,0.045)]";
const currency = (value: number, mode: CurrencyDisplayMode) => formatCompactVnd(value, mode);

export type AllocationGroup = { id: string; name: string; value: number; assetCount: number; color: string };

export function InteractiveValueAllocation({ title, context, data, totalValue, isLoading, currencyMode, accent, selectedId, onSelect }: { title: string; context?: string; data: AllocationGroup[]; totalValue: number; isLoading: boolean; currencyMode: CurrencyDisplayMode; accent: string; selectedId: string | null; onSelect: (item: AllocationGroup) => void }) {
  const topItems = data.slice(0, 5);
  const remaining = Math.max(0, data.length - topItems.length);
  return <section className={`mt-5 ${card} overflow-hidden`}><div className="flex items-center justify-between gap-3 border-b border-[#E7EEF3] px-4 py-3"><div className="min-w-0"><div className="flex items-center gap-2 text-sm font-extrabold text-[#193B57]"><PieChartIcon size={16} style={{ color: accent }} />{title}</div>{context && <p className="mt-0.5 truncate text-[11px] text-[#71869A]">Phạm vi: {context}</p>}</div><div className="shrink-0 text-right"><div className="text-[9px] font-extrabold uppercase tracking-[.1em] text-[#8AA0B6]">Tổng giá trị</div><div className="mt-0.5 text-xs font-extrabold text-[#102A43]">{currency(totalValue, currencyMode)}</div></div></div>{isLoading ? <div className="grid min-h-32 place-items-center text-xs text-[#71869A]">Đang tổng hợp dữ liệu...</div> : !data.length || totalValue <= 0 ? <div className="grid min-h-32 place-items-center px-5 text-center text-xs text-[#71869A]">Chưa có giá trị tài sản để phân bổ trong phạm vi này.</div> : <div className="grid gap-4 p-4 sm:grid-cols-[124px_minmax(0,1fr)] sm:items-center"><InteractiveAllocationDonut data={data} totalValue={totalValue} selectedId={selectedId} onSelect={onSelect} /><div className="min-w-0 divide-y divide-[#EDF2F5]">{topItems.map((item) => { const percentage = totalValue ? Math.round((item.value / totalValue) * 100) : 0; const selected = item.id === selectedId; return <button key={item.id} type="button" onClick={() => onSelect(item)} aria-pressed={selected} className={`grid w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-3 py-2 text-left transition first:pt-0 last:pb-0 ${selected ? "rounded-md bg-[#F0F7FF] px-2" : "hover:bg-[#F8FBFC]"}`}><div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><span className="h-2 w-2 shrink-0 rounded-full" style={{ backgroundColor: item.color }} /><span className="truncate text-xs font-bold text-[#193B57]">{item.name}</span><span className="shrink-0 text-[10px] text-[#8AA0B6]">{item.assetCount} TS</span></div><div className="mt-1 h-1 overflow-hidden rounded-full bg-[#EAF0F4]"><div className="h-full rounded-full" style={{ width: `${Math.max(3, percentage)}%`, backgroundColor: item.color }} /></div></div><div className="text-right"><div className="text-xs font-extrabold text-[#102A43]">{percentage}%</div><div className="mt-0.5 text-[10px] font-semibold text-[#60758A]">{currency(item.value, currencyMode)}</div></div></button>; })}{remaining > 0 && <p className="pt-2 text-[10px] font-semibold text-[#71869A]">+ {remaining} nhóm còn lại: nhấn trực tiếp trên biểu đồ để xem tài sản.</p>}</div></div>}</section>;
}

function InteractiveAllocationDonut({ data, totalValue, selectedId, onSelect }: { data: AllocationGroup[]; totalValue: number; selectedId: string | null; onSelect: (item: AllocationGroup) => void }) {
  let startAngle = -90;
  const point = (angle: number) => { const radians = (angle * Math.PI) / 180; return { x: 50 + 46 * Math.cos(radians), y: 50 + 46 * Math.sin(radians) }; };
  return <div className="relative mx-auto h-28 w-28"><svg viewBox="0 0 100 100" className="h-28 w-28 overflow-visible" aria-label="Biểu đồ phân bổ có thể chọn nhóm">{data.map((item) => { const percentage = totalValue ? (item.value / totalValue) * 100 : 0; const endAngle = startAngle + percentage * 3.6; const start = point(startAngle); const end = point(endAngle); const largeArc = endAngle - startAngle > 180 ? 1 : 0; const isSingle = percentage >= 99.999; const selected = item.id === selectedId; const path = `M 50 50 L ${start.x} ${start.y} A 46 46 0 ${largeArc} 1 ${end.x} ${end.y} Z`; startAngle = endAngle; const interactions = { role: "button", tabIndex: 0, "aria-label": `Xem tài sản nhóm ${item.name}`, onClick: () => onSelect(item), onKeyDown: (event: any) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onSelect(item); } } }; return isSingle ? <circle key={item.id} cx="50" cy="50" r="46" fill={item.color} {...interactions} className="cursor-pointer transition-opacity hover:opacity-80" style={{ stroke: selected ? "#102A43" : "white", strokeWidth: selected ? 3 : 1 }} /> : <path key={item.id} d={path} fill={item.color} {...interactions} className="cursor-pointer transition-opacity hover:opacity-80" style={{ stroke: selected ? "#102A43" : "white", strokeWidth: selected ? 2.5 : 1 }} />; })}<circle cx="50" cy="50" r="29" fill="white" pointerEvents="none" /></svg><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><div className="text-[9px] font-bold uppercase tracking-[.08em] text-[#8AA0B6]">Nhóm</div><div className="font-display text-xl font-extrabold text-[#102A43]">{data.length}</div></div></div></div>;
}

export function AllocationAssetDetails({ groupLabel, groupName, assets, currencyMode, onClose }: { groupLabel: string; groupName: string; assets: Array<{ id: number; assetCode: string; name: string; departmentName: string; holderName: string | null; purchaseValue: string | number | null }>; currencyMode: CurrencyDisplayMode; onClose: () => void }) {
  const total = assets.reduce((sum, asset) => sum + Number(asset.purchaseValue || 0), 0);
  return <section className={`mt-5 overflow-hidden ${card}`}><div className="flex flex-col gap-3 border-b border-[#E7EEF3] px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2 text-sm font-extrabold text-[#193B57]"><FileBarChart size={16} className="text-[#2666A8]" />Tài sản thuộc {groupLabel}: <span className="truncate text-[#2666A8]">{groupName}</span></div><p className="mt-1 text-[11px] text-[#71869A]">{assets.length} tài sản · Tổng giá trị {currency(total, currencyMode)}</p></div><button type="button" onClick={onClose} className="rounded-md border border-[#DDE7F0] bg-white px-3 py-1.5 text-xs font-bold text-[#60758A] hover:bg-[#F7FAFC]">Đóng danh sách</button></div>{assets.length ? <div className="mobile-table-scroll overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-[#FBFCFD] text-[10px] uppercase tracking-[.1em] text-[#8AA0B6]"><tr><th className="px-4 py-3">Tài sản</th><th className="px-3 py-3">Phòng Ban</th><th className="px-3 py-3">Người giữ</th><th className="px-4 py-3 text-right">Giá trị</th></tr></thead><tbody>{assets.map((asset) => <tr key={asset.id} className="border-t border-[#EDF2F5] hover:bg-[#F8FBFC]"><td className="px-4 py-3"><div className="font-bold text-[#193B57]">{asset.name}</div><div className="mt-0.5 font-mono text-[10px] text-[#8AA0B6]">{asset.assetCode}</div></td><td className="px-3 py-3 text-[#60758A]">{asset.departmentName}</td><td className="px-3 py-3 text-[#60758A]">{asset.holderName || "Chưa cấp phát"}</td><td className="px-4 py-3 text-right font-extrabold text-[#102A43]">{currency(Number(asset.purchaseValue || 0), currencyMode)}</td></tr>)}</tbody></table></div> : <p className="px-4 py-8 text-center text-xs text-[#8AA0B6]">Không có tài sản phù hợp trong nhóm này.</p>}</section>;
}
