// @ts-nocheck
import { useState } from "react";
import { FileBarChart, X } from "lucide-react";
import { formatCompactVnd, type CurrencyDisplayMode } from "@/lib/formatters";

const card = "rounded-xl border border-[#DFE9F0] bg-white shadow-[0_8px_24px_rgba(16,42,67,0.045)]";
const currency = (value: number, mode: CurrencyDisplayMode) => formatCompactVnd(value, mode);
const formatDate = (value: unknown) => value ? new Date(value as string | number | Date).toLocaleDateString("vi-VN") : "—";
const statusLabels: Record<string, string> = { available: "Sẵn có", assigned: "Đang cấp phát", maintenance: "Bảo hành/Sửa chữa", retired: "Khấu hao/Thanh lý", lost: "Thất lạc", returned_to_vendor: "Đã trả nhà cung cấp" };
const conditionLabels: Record<string, string> = { good: "Tốt", fair: "Khá", needs_inspection: "Cần kiểm tra", damaged: "Hư hỏng" };

export function InteractiveAllocationAssetDetails({ groupLabel, groupName, assets, currencyMode, onClose }: { groupLabel: string; groupName: string; assets: any[]; currencyMode: CurrencyDisplayMode; onClose: () => void }) {
  const [selectedAsset, setSelectedAsset] = useState<any>(null);
  const total = assets.reduce((sum, asset) => sum + Number(asset.purchaseValue || 0), 0);
  const openAsset = (asset: any) => setSelectedAsset(asset);
  return <><section className={`mt-5 overflow-hidden ${card}`}><div className="flex flex-col gap-3 border-b border-[#E7EEF3] px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2 text-sm font-extrabold text-[#193B57]"><FileBarChart size={16} className="text-[#2666A8]" />Tài sản thuộc {groupLabel}: <span className="truncate text-[#2666A8]">{groupName}</span></div><p className="mt-1 text-[11px] text-[#71869A]">Nhấn vào từng dòng để xem đầy đủ thông tin · {assets.length} tài sản · Tổng giá trị {currency(total, currencyMode)}</p></div><button type="button" onClick={onClose} className="rounded-md border border-[#DDE7F0] bg-white px-3 py-1.5 text-xs font-bold text-[#60758A] hover:bg-[#F7FAFC]">Đóng danh sách</button></div>{assets.length ? <div className="mobile-table-scroll overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-[#FBFCFD] text-[10px] uppercase tracking-[.1em] text-[#8AA0B6]"><tr><th className="px-4 py-3">Tài sản</th><th className="px-3 py-3">Phòng Ban</th><th className="px-3 py-3">Người giữ</th><th className="px-4 py-3 text-right">Giá trị</th></tr></thead><tbody>{assets.map((asset) => <tr key={asset.id} role="button" tabIndex={0} aria-label={`Xem chi tiết tài sản ${asset.name}`} onClick={() => openAsset(asset)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); openAsset(asset); } }} className="cursor-pointer border-t border-[#EDF2F5] outline-none transition hover:bg-[#F0F7FF] focus-visible:bg-[#F0F7FF]"><td className="px-4 py-3"><div className="font-bold text-[#193B57]">{asset.name}</div><div className="mt-0.5 font-mono text-[10px] text-[#8AA0B6]">{asset.assetCode}</div></td><td className="px-3 py-3 text-[#60758A]">{asset.departmentName}</td><td className="px-3 py-3 text-[#60758A]">{asset.holderName || "Chưa cấp phát"}</td><td className="px-4 py-3 text-right font-extrabold text-[#102A43]">{currency(Number(asset.purchaseValue || 0), currencyMode)}</td></tr>)}</tbody></table></div> : <p className="px-4 py-8 text-center text-xs text-[#8AA0B6]">Không có tài sản phù hợp trong nhóm này.</p>}</section>{selectedAsset && <AssetDetailPopup asset={selectedAsset} currencyMode={currencyMode} onClose={() => setSelectedAsset(null)} />}</>;
}

function AssetDetailPopup({ asset, currencyMode, onClose }: { asset: any; currencyMode: CurrencyDisplayMode; onClose: () => void }) {
  const rows = [
    ["Mã tài sản", asset.assetCode], ["Trạng thái", statusLabels[asset.status] || asset.status || "—"], ["Tình trạng", conditionLabels[asset.condition] || asset.condition || "—"], ["Phân loại", asset.categoryName || "Chưa phân loại"], ["Phòng Ban", asset.departmentName || "Chưa gán"], ["Bộ Phận", asset.divisionName || "Chưa gán"], ["Người giữ", asset.holderName || "Chưa cấp phát"], ["Hãng", asset.brandName || "Chưa gán Hãng"], ["Nhà cung cấp", asset.vendor || "Chưa gán Nhà cung cấp"], ["Ngày mua", formatDate(asset.purchaseDate)], ["Nguyên giá", currency(Number(asset.purchaseValue || 0), currencyMode)], ["Serial/IMEI", asset.serialNumber || "—"], ["Vị trí", asset.location || "—"], ["Hạn bảo hành", formatDate(asset.warrantyUntil)], ["Ngày cập nhật", formatDate(asset.updatedAt)],
  ];
  return <><button type="button" aria-label="Đóng chi tiết tài sản" onClick={onClose} className="fixed inset-0 z-[70] bg-[#102A43]/35 backdrop-blur-[1px]" /><section role="dialog" aria-modal="true" aria-label={`Chi tiết tài sản ${asset.name}`} className="fixed inset-x-3 top-1/2 z-[71] max-h-[88vh] w-auto -translate-y-1/2 overflow-y-auto rounded-2xl border border-[#DFE9F0] bg-white p-5 shadow-2xl sm:left-1/2 sm:right-auto sm:w-full sm:max-w-2xl sm:-translate-x-1/2 sm:p-6"><button type="button" onClick={onClose} aria-label="Đóng popup chi tiết tài sản" className="absolute right-4 top-4 grid h-8 w-8 place-items-center rounded-md text-[#71869A] hover:bg-[#F0F5F8]"><X size={17} /></button><div className="pr-12"><div className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[#2666A8]">Thông tin tài sản</div><h2 className="mt-2 font-display text-2xl font-extrabold text-[#102A43]">{asset.name}</h2><p className="mt-1 font-mono text-xs font-bold text-[#2666A8]">{asset.assetCode}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label} className="rounded-lg border border-[#E7EEF3] bg-[#FBFCFD] px-3 py-2.5"><div className="text-[9px] font-extrabold uppercase tracking-[.1em] text-[#8AA0B6]">{label}</div><div className="mt-1 break-words text-xs font-bold text-[#193B57]">{value}</div></div>)}</div>{asset.note && <section className="mt-4 rounded-lg border border-[#E7EEF3] bg-[#F8FBFC] p-3"><div className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#60758A]">Ghi chú</div><p className="mt-1.5 whitespace-pre-wrap text-xs leading-5 text-[#4B6276]">{asset.note}</p></section>}{asset.maintenanceReason && <section className="mt-3 rounded-lg border border-[#F2D596] bg-[#FFF9EB] p-3"><div className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#A86B00]">Lý do Bảo hành/Sửa chữa</div><p className="mt-1.5 whitespace-pre-wrap text-xs leading-5 text-[#8F5A00]">{asset.maintenanceReason}</p></section>}</section></>;
}
