import { useState } from "react";
import { ExternalLink, Link2, X } from "lucide-react";

type LinkedAsset = { id: number; assetCode: string; name: string; serialNumber?: string | null };

export function InvoiceLinkedAssetQuickLinks({ assets }: { assets: LinkedAsset[] }) {
  const [selectedAsset, setSelectedAsset] = useState<LinkedAsset | null>(null);
  if (!assets.length) return null;
  return <><section className="mt-4 rounded-xl border border-[#C9DDF5] bg-[#F4F9FF] p-3" data-invoice-linked-asset-links="true"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs font-extrabold text-[#193B57]"><Link2 size={14} className="text-[#2666A8]" />Tài sản liên kết</div><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold text-[#2666A8]">{assets.length} tài sản</span></div><div className="mt-2 flex flex-wrap gap-1.5">{assets.map((asset) => <button key={asset.id} type="button" onClick={() => setSelectedAsset(asset)} className="inline-flex max-w-full items-center gap-1 rounded-md border border-[#C9DDF5] bg-white px-2 py-1 text-left text-[10px] font-bold text-[#2666A8] transition hover:border-[#79A9DE] hover:bg-[#EAF3FF] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#2666A8]"><span className="font-mono">{asset.assetCode}</span><span className="truncate">· {asset.name}</span><ExternalLink size={11} className="shrink-0" /></button>)}</div></section>{selectedAsset && <><button type="button" aria-label="Đóng xem nhanh Tài sản" onClick={() => setSelectedAsset(null)} className="fixed inset-0 z-[185] bg-[#102A43]/40 backdrop-blur-sm" /><section role="dialog" aria-modal="true" aria-label={`Xem nhanh Tài sản ${selectedAsset.assetCode}`} className="fixed left-1/2 top-1/2 z-[186] w-[calc(100%-2rem)] max-w-md -translate-x-1/2 -translate-y-1/2 rounded-2xl border border-[#DFE9F0] bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><div className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[#2666A8]">Tài sản liên kết Hóa đơn</div><h3 className="mt-1 text-lg font-extrabold text-[#102A43]">{selectedAsset.name}</h3><p className="mt-1 font-mono text-xs font-bold text-[#2666A8]">{selectedAsset.assetCode}</p></div><button type="button" onClick={() => setSelectedAsset(null)} className="drawer-close-action" aria-label="Đóng"><X size={18} /></button></div><dl className="mt-5 grid gap-3 rounded-xl border border-[#E7EEF3] bg-[#FBFCFD] p-4 text-xs"><div><dt className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#8AA0B6]">Mã Tài sản</dt><dd className="mt-1 font-mono font-bold text-[#193B57]">{selectedAsset.assetCode}</dd></div><div><dt className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#8AA0B6]">Serial/IMEI</dt><dd className="mt-1 font-bold text-[#193B57]">{selectedAsset.serialNumber || "Chưa có"}</dd></div></dl><div className="mt-5 flex justify-end"><button type="button" onClick={() => setSelectedAsset(null)} className="modal-close-action">Đóng</button></div></section></>}</>;
}
