import { ArrowDown, ArrowUp, GripVertical, RotateCcw } from "lucide-react";
import { useState } from "react";

type MenuOrderItem = { label: string };

export function MenuOrderSettings({ items, onMove, onReorder, onReset, isSaving = false }: { items: MenuOrderItem[]; onMove: (index: number, direction: -1 | 1) => void; onReorder: (labels: string[]) => void; onReset: () => void; isSaving?: boolean }) {
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  const reorder = (targetIndex: number) => {
    if (draggedIndex === null || draggedIndex === targetIndex) return;
    const next = [...items];
    const [moved] = next.splice(draggedIndex, 1);
    next.splice(targetIndex, 0, moved);
    onReorder(next.map((item) => item.label));
  };
  return <section className="mx-auto mb-8 max-w-[1100px] rounded-xl border border-[#DFE9F0] bg-white p-5 shadow-[0_8px_24px_rgba(16,42,67,.045)] sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#ECF8F7] text-[#087A6A]"><GripVertical size={18} /></div><div><h2 className="font-display text-base font-extrabold text-[#102A43]">Thứ tự menu điều hướng</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-[#71869A]">Kéo thả hoặc dùng mũi tên để đổi vị trí. Thiết lập được đồng bộ theo tài khoản và áp dụng ngay trên sidebar.</p></div></div><button type="button" disabled={isSaving} onClick={onReset} className="filter-action shrink-0"><RotateCcw size={14} />{isSaving ? "Đang lưu..." : "Khôi phục mặc định"}</button></div><ol className="mt-5 grid gap-2" aria-label="Danh sách thứ tự menu">{items.map((item, index) => <li key={item.label} draggable={!isSaving} onDragStart={(event) => { setDraggedIndex(index); event.dataTransfer.effectAllowed = "move"; }} onDragOver={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = "move"; }} onDrop={(event) => { event.preventDefault(); reorder(index); setDraggedIndex(null); }} onDragEnd={() => setDraggedIndex(null)} className={`flex min-w-0 items-center gap-2 rounded-lg border px-2.5 py-2 transition ${draggedIndex === index ? "border-[#8BCDC6] bg-[#F4FBFA] opacity-60" : "border-[#E7EEF3] bg-[#FBFCFD]"}`}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-md bg-[#EAF3FF] font-mono text-[10px] font-extrabold text-[#2666A8]">{String(index + 1).padStart(2, "0")}</span><span className="grid h-7 w-5 shrink-0 cursor-grab place-items-center text-[#8AA0B6] active:cursor-grabbing" title="Kéo để sắp xếp" aria-label={`Kéo ${item.label} để sắp xếp`}><GripVertical size={15} /></span><span className="min-w-0 flex-1 truncate text-xs font-bold text-[#193B57]">{item.label}</span><div className="flex shrink-0 gap-1"><button type="button" disabled={isSaving || index === 0} onClick={() => onMove(index, -1)} aria-label={`Đưa ${item.label} lên`} title="Đưa lên" className="grid h-7 w-7 place-items-center rounded-md border border-[#DDE7F0] text-[#60758A] transition hover:border-[#8BCDC6] hover:bg-[#F4FBFA] hover:text-[#087A6A] disabled:cursor-not-allowed disabled:opacity-35"><ArrowUp size={14} /></button><button type="button" disabled={isSaving || index === items.length - 1} onClick={() => onMove(index, 1)} aria-label={`Đưa ${item.label} xuống`} title="Đưa xuống" className="grid h-7 w-7 place-items-center rounded-md border border-[#DDE7F0] text-[#60758A] transition hover:border-[#8BCDC6] hover:bg-[#F4FBFA] hover:text-[#087A6A] disabled:cursor-not-allowed disabled:opacity-35"><ArrowDown size={14} /></button></div></li>)}</ol></section>;
}
